name: shoefrk_admin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^1.10.7
  flutter_riverpod: ^2.0.0
  intl: ^0.18.1
  fl_chart: ^0.63.0
  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.4
  shimmer: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
